# Generated by Django 2.1.7 on 2019-02-22 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(help_text='Nombre del producto', max_length=200)),
                ('precio_unitario', models.DecimalField(decimal_places=0, help_text='Precio', max_digits=12)),
                ('cantidad', models.IntegerField(help_text='Cantidad')),
                ('categoria_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='categoria.Categoria')),
            ],
        ),
    ]
