# Generated by Django 2.1.7 on 2019-03-20 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_producto_fecha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='categoria_id',
            new_name='categoria',
        ),
    ]
